version: 2
jobs:
  Test:
    docker:
      - image: golang:1.11
    steps:
      - checkout
      - run: make coverage
      - run: make
      - run: make coveralls
workflows:
  version: 2
  CI:
    jobs:
      - Test
